version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./project:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/config/drupal.conf:/etc/nginx/conf.d/drupal.conf
    links:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    networks:
      - internal
    volumes:
      - ./project/:/var/www/html/
      - ./logs/php:/var/log

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/datas:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: mydatabase

  mariadb:
    build:
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mariadb/datas:/var/lib/mysql
    networks:
      - internal
    ports:
      - 3306:3306

networks:
  internal:
    driver: bridge
